version: "1"

config:
  app:
    ui: true
    port: 8080

  user:
    enabled: true
    id: pk
    email: true
    phone_number: true
    login_method: jwt 
    jwt_token: "T6PIosO0g6Mq/aJSLpAPn8XKKTnWqpvfJL6WHymPMAH="

  models:
    default:
      id: uuid
      created_at: ture
      updated_at: ture
      deleted_at: ture
      owner: true

    product:
      name: str
      description: str
      price: float
      discount: float
      image: str
      total: float

    order:
      user_id: fk
      total: float

    line_item:
      product_id: fk
      order_id: fk
      qty: int
      total: float
      account: float
          